pacman:
	python pacman.py -p ReflexAgent -l testClassic
multiagent:
	python pacman.py -p MinimaxAgent -l minimaxClassic -a depth=4
q1:
	python autograder.py -q q1 --no-graphics
q2:
	python autograder.py -q q2 --no-graphics
q3:
	python autograder.py -q q3 --no-graphics
q4:
	python autograder.py -q q4 --no-graphics
mazes: ## make all mazes
	python autograder.py
